# © 2026 Strategos Pty Ltd. All rights reserved.
# Aut Viam Inveniam Aut Faciam

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sarissa"
version = "1.0.1"
description = "Rapid-access CTF dashboard for digital forensics competitions. by ShadowStrike."
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Strategos", email = "r@strategos.au"}
]
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 1 - Planning",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "fastapi",
    "uvicorn",
    "python-magic",
    "python-magic-bin; sys_platform == 'win32'",
    "rich",
]

[project.optional-dependencies]
test = ["pytest", "httpx"]

[project.scripts]
sarissa = "sarissa.main:main"

[project.urls]
"Source" = "https://github.com/ShadowStrike-CTF/sarissa"

[tool.hatch.build.targets.wheel]
packages = ["src/sarissa"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
